### PR TITLE
Cloudlink Suite

### LINKED ISSUE #60: Finish rewrite of Cloudlink suite
^

### PR DESCRIPTION
**Pull request by showierdata9978**
Cloudlink SUIT impl

resolves #60

### CODE REVIEW

**Comment by MikeDev101** [comment]
Too early, please wait for CL 0.1.9.0 (CL4 Optimized).
(Will be published by the end of today)

**Comment by showierdata9978** [comment]
> Too early, please wait for CL 0.1.9.0 (CL4 Optimized). (Will be published by the end of today)

Its its own system in its entirety lmao (il fix breaking changes that are made anyways).

**Comment by showierdata9978** [comment]
and, yes im still working on this lmao

**Comment by showierdata9978** [comment]
editing for optimized now

**Comment by showierdata9978** [comment]
testing

**Comment by MikeDev101** [comment]
Needs some code refactoring, and send_packet should be replaced with send_packet_unicast with proper message quirks

**Comment by showierdata9978** [comment]
>and send_packet should be replaced with send_packet_unicast with proper message quirks
wont work because send_packet_unicast forces a command

**Comment by showierdata9978** [comment]
you also gave nothing to go off of for refactoring.

**Comment by showierdata9978** [comment]
also, drafts are not ment for this, drafts are ment when the writer is still writing. github also has its own review system

**Comment by MikeDev101** [comment]
> you also gave nothing to go off of for refactoring.

```python
await self.send_packet_unicast(
            client = client,
            cmd = "auth",
            val = {
                "username": client.friendly_username,
                "token": usr['session']['token'],
                "refresh_token": usr['session']['refresh_token']
            },
            quirk = self.supporter.quirk_update_msg
        )
```

This will generate the following message JSON:
```json
{
                 "cmd": "auth"
                 "username": client.friendly_username,
                 "token": usr['session']['token'],
                 "refresh_token": usr['session']['refresh_token'],
}
```



> also, drafts are not ment for this, drafts are ment when the writer is still writing. github also has its own review system

I marked it as a draft since it wasn't ready yet. Might just be my mistake. Oh well.

**Comment by MikeDev101** [comment]
> ```python
> await self.send_packet_unicast(
>             client = client,
>             cmd = "auth",
>             val = {
>                 "username": client.friendly_username,
>                 "token": usr['session']['token'],
>                 "refresh_token": usr['session']['refresh_token']
>             },
>             quirk = self.supporter.quirk_update_msg
>         )
> ```
> 
> This will generate the following message JSON:
> 
> ```json
> {
>                  "cmd": "auth"
>                  "username": client.friendly_username,
>                  "token": usr['session']['token'],
>                  "refresh_token": usr['session']['refresh_token'],
> }
> ```

If you leave the message quirks unspecified or set to quirk_embed_val, the payload will look like this:

```json
 {
                  "cmd": "auth",
                  "val": {
                                    "username": client.friendly_username,
                                    "token": usr['session']['token'],
                                    "refresh_token": usr['session']['refresh_token'],
                  }
 }
 ```

**Comment by showierdata9978** [comment]
> > \<snip\>
> 
> If you leave the message quirks unspecified or set to quirk_embed_val, the payload will look like this:
> 
> ```json
>  {
>                   "cmd": "auth",
>                   "val": {
>                                     "username": client.friendly_username,
>                                     "token": usr['session']['token'],
>                                     "refresh_token": usr['session']['refresh_token'],
>                   }
>  }
> ```

thats slightly annoying tbh. most ppl would expect the other way arround from cl4 unoptimised

**Comment by MikeDev101** [comment]
CL4 unoptimized, or rather, any previous instance of CL4 wasn't intended for production usage, and I haven't provided docs for it until it was mature enough for production use (CL4 optimized). There's a reason why I called CL4-related releases "Early Release", as to give an idea of what to expect. Either way, I'll port this code to utilize CL4 optimized.

For the love of Meowy, just wait for docs to get finished...

**Comment by showierdata9978** [comment]
> CL4 unoptimized, or rather, any previous instance of CL4 wasn't intended for production usage, and I haven't provided docs for it until it was mature enough for production use (CL4 optimized). There's a reason why I called CL4-related releases "Early Release", as to give an idea of what to expect. Either way, I'll port this code to utilize CL4 optimized.
> 
> For the love of Meowy, just wait for docs to get finished...

Suit is mostly ported

**Comment by MikeDev101** [comment]
Btw... (In the style of stocktales):

Suit = 
suit_example

Suite = 
suite_example

**Spelling counts.**

**Comment by showierdata9978** [comment]
> > also, drafts are not ment for this, drafts are ment when the writer is still writing. github also has its own review system
> 
> I marked it as a draft since it wasn't ready yet. Might just be my mistake. Oh well.

image

**Comment by showierdata9978** [comment]
Suite is going major renovations right now.

**Comment by MikeDev101** [comment]
Code will need to have refactoring to accommodate changes to how listeners work.

`listener_detected` and `listener_id` have been simplified into `listener` as of 4.0-stable1

**Comment by OhNoItzBuster** [comment]
let's go, suite is coming back

**Comment by showierdata9978** [comment]
restarting on this

**Pull request closed without merging**
