### PR TITLE
Fixing #23

### PR DESCRIPTION
**Pull request by showierdata9978**
I only added 5 lines of code for this 
https://github.com/MikeDev101/cloudlink/issues/23

### CODE REVIEW

**Comment by MikeDev101** [comment]
Usernames can only be set once per connection, this code doesn't take that into account.

**Comment by showierdata9978** [comment]
> Usernames can only be set once per connection, this code doesn't take that into account.

Hmmm, maybe use a Python dict with hashed IPs as the key and use time.time() as the data, then use that as the if statement, although I don't know how to get it with python, and u take the IP In other functions. (only when the client sets the username)

**Comment by showierdata9978** [comment]
> > Usernames can only be set once per connection, this code doesn't take that into account.
> 
> Hmmm, maybe use a Python dict with hashed IPs as the key and use time.time() as the data, then use that as the if statement, although I don't know how to get it with python, and u take the IP In other functions. (only when the client sets the username)

found the IP finder

**Comment by showierdata9978** [comment]
no actively, here , i added code to this pull request

**Comment by showierdata9978** [comment]
Hello? I updated the code.

**Comment by MikeDev101** [comment]
After watching a server catch fire, yer is broken, mate.

**Comment by Bloctans** [comment]
did you do a typo? time.Time doesnt exist in python.

**Comment by showierdata9978** [comment]
Typo

**Comment by showierdata9978** [comment]
fixed typo in my fork

**Pull request merged**
