### PR TITLE
Cloudlink Suite

### LINKED ISSUE #60: Finish rewrite of Cloudlink suite
^

### PR DESCRIPTION
**Pull request by showierdata9978**
## 🔴  not ready to pull 🔴 
just not a draft for so mike can review

### Done:
- Home server side auth (1 commit untested)
- CloudDisk Home Server
- Server CA connection (untested due to using github.dev and phone being dead again)

### not planned fetures
   - Client Side SDK`s
   - cloudcoin

### CODE REVIEW

**Comment by MikeDev101** [comment]
Servers use the WSS:// protocol string.

**Comment by showierdata9978** [comment]
> Servers _should_ use the WSS:// protocol string.

ye, local testin tho so i dont have wss

**Comment by MikeDev101** [comment]
> > Servers _should_ use the WSS:// protocol string.
> 
> this is home server btw
> 
> what im asking is, how shoud other servers connect to home (clients alr connect via websockets)

Servers use the same protocol, they just need to run a client alongside the server and conditionally transfer messages

**Comment by showierdata9978** [comment]
Currently the client logs into the home server, logs in and gets a token to
login to the non home server btw (the non home server then asks the home
server what user is associated with this token ` not implemented`)

**Comment by showierdata9978** [comment]
Oh, and did you see the test server I have public on replit? (#92)

**Comment by asherlr23** [comment]
> currently untested due to using github.dev

Can’t you just make a code space?

**Comment by showierdata9978** [comment]
I prefer to not use code spaces, as they cost money where I can just spin
up a repl on my phone (it was dead yesterday)

I also have replit hacker for free

**Comment by asherlr23** [comment]
> I prefer to not use code spaces, as they cost money where I can just spin up a repl on my phone (it was dead yesterday) I also have replit hacker for free
> […](#)

1) how did you get free replit hacker? (without cycles, replit is pretty much.net fiddle)

2) code. Spaces are literally free. Go to your repository, click code, click code spaces, then click the plus icon at the top of the box.

I have never paid for anything from github in my entire life

**Comment by asherlr23** [comment]
Yes, I know that the urls are extremely weird

**Comment by showierdata9978** [comment]
GitHub education lmao

**Comment by asherlr23** [comment]
I don’t have github education.

**Comment by showierdata9978** [comment]
If your in highschool or college you can apply for it

**Comment by asherlr23** [comment]
Ok and? All I’m saying is that you don’t need a subscription for codespaces, it’s free.

**Comment by showierdata9978** [comment]
> Ok and? All I’m saying is that you don’t need a subscription for codespaces, it’s free.

Up to a certain point, then you need to pay

**Comment by asherlr23** [comment]
wait really

**Comment by showierdata9978** [comment]
> wait really

Ye

**Comment by asherlr23** [comment]
> > Ok and? All I’m saying is that you don’t need a subscription for codespaces, it’s free.
> 
> Up to a certain point, then you need to pay

Just don’t code for a total 120 hours (see https://github.com/settings/billing/plans )

**Comment by showierdata9978** [comment]
ready for review, but not for pulling

**Comment by showierdata9978** [comment]
I'm actually going to test this now

**Comment by showierdata9978** [comment]
This is basically ready to pull, but the SDK does not work bc of some bugs within cloudlink.

**Comment by showierdata9978** [comment]
edited above for discord

**Comment by MikeDev101** [comment]
Test suite must be created to verify functionality. Will not merge if there is buggy/missing functions.

**Comment by showierdata9978** [comment]
> Test suite must be created to verify functionality. Will not merge if there is buggy/missing functions.

Cloudlink itself has bugs that make the server suit impossible to create

**Comment by showierdata9978** [comment]
example: statuscode does not get called. nor does the connection callback

**Comment by MikeDev101** [comment]
> example: statuscode does not get called. nor does the connection callback

Will look into this issue.

**Comment by showierdata9978** [comment]
also, a pain to init the client, as i dont use parent, and dont have it

**Pull request closed without merging**
